### ISSUE TITLE
Getting issue while storing the decimal value in the document.

### ISSUE THREAD

**Issue by harshalizode** [dymmond/mongoz#42]
Hello,

I am trying to store the decimal value in by embedded document:

```
Class Achived(Document):
    score_from: float = mongoz.Decimal
    score_to: float = mongoz.Decimal(max_digits=5, decimal_places=3)
    amount: float = mongoz.Decimal(
        max_digits=5, decimal_places=3)
```

When I try to store the decimal value it raise the exception as:
`InvalidDocument("cannot encode object: Decimal('0.60'), of type: <class 'decimal.Decimal'>")`
.
As I passing the string or float value for it to store in document.

**Comment by tarsil** [comment]
I will have a look but please give me an example of something you are trying to store to run against

**Comment by harshalizode** [comment]
I am firing the query as
`await Achived.objects.create(score_from=0.60, score_to='0.90', amount='78.6786')`

But it causing the error if I convert the decimal values in the `decimal.Decimal` object then it requires the type string, integer or float.

**Comment by tarsil** [comment]
@harshalizode correct, Pymongo doesn't understand the native Decimal, for some reason they didn't do an internal implementation. So they use a Decimal128, which is now being supported internally by the version 0.10.1.

If you install that one, this issue should be now fixed.

**Comment by tarsil** [comment]
The docs were also updated with some extra explanations, but the way you do remains the same 👍🏼

**Comment by tarsil** [comment]
@harshalizode something for the embedded documents was missing from release 0.10.1 for the decimal as well, now it is updated in the 0.10.2, apologies for that.

**Comment by harshalizode** [comment]
Yes, It has been solved in the latest version.

**Comment by harshalizode** [comment]
max_digits and decimal_places are required for DecimalField?

**Comment by tarsil** [comment]
> max_digits and decimal_places are required for DecimalField?

Yes

**Comment by harshalizode** [comment]
Okay

**Comment by harshalizode** [comment]
While updating the decimal field it raises the exception as:
`InvalidDocument("cannot encode object: Decimal('0.30'), of type: <class 'decimal.Decimal'>")`

But with creation, it works fine.

**Comment by tarsil** [comment]
Hmm, maybe I missed that part. Let me have a quick look

**Comment by tarsil** [comment]
@harshalizode apologies but we have been very very busy. Tomorrow it will be released

**Comment by tarsil** [comment]
@harshalizode release 0.10.4 its now live and all of these are addressed. Apologies for the time but again, we have been very busy.

**Comment by harshalizode** [comment]
Thank you for release :)

**Comment by harshalizode** [comment]
@tarsil is it fixed?
After updating the Mongoz 0.10.3 to 0.10.4 facing the same issue.

**Comment by tarsil** [comment]
@harshalizode why was this reopened? The tests are passing for that. Version 0.10.4 has this:

https://github.com/dymmond/mongoz/blob/main/tests/models/manager/test_decimal.py#L62

See how it was done. If the problem remains, please provide a proper example to replicate

**Comment by harshalizode** [comment]
Hello @tarsil ,
I have write the test case for the decimal field updation and it is still failing with the latest version of the Mongoz.

```
import mongoz
from typing import List
from esmerald.conf import settings
from decimal import Decimal


class Badges(mongoz.EmbeddedDocument):
    score: Decimal = mongoz.Decimal(max_digits=5, decimal_places=2, null=True)
    name: str = mongoz.String()


class Achievement(mongoz.Document):
    name: str = mongoz.String()
    total_score: Decimal = mongoz.Decimal(max_digits=5, decimal_places=2, null=True)  # noqa
    badges: List[Badges] = mongoz.Array(Badges, null=True)

    class Meta:
        registry = settings.default_registry
        database = settings.application_db


async def test_decimal_on_update() -> None:
    try:
        badges = [{
            "name": "badge1",
            "score": "32083.33"
        }]
        await Achievement.objects.create(name="Batman", total_score="22.246")

        arch = await Achievement.objects.last()

        arch.total_score = Decimal("28")
        await arch.save()

        arch = await Achievement.objects.last()

        await arch.update(total_score=Decimal("30"))

        arch = await Achievement.objects.last()

        await Achievement.objects.filter().update(total_score=Decimal("40"),
                                                  badges=badges)

        arch = await Achievement.objects.last()
    except Exception as error:
        assert False, error
```

**Comment by harshalizode** [comment]
Yes, that is corrected now, but updating the decimal field requires only the decimal object, whereas creation will accept the string/integer.

**Comment by tarsil** [comment]
@harshalizode it was like this since version 0.10.4. The reason for that it's because internally the update is more complex than the simple create. It is planned to be updated in the future but for now this is the way

**Comment by harshalizode** [comment]
Okay.
